[package]
name = "basedbot"
version = "0.1.0"
authors = ["kageru <kageru@encode.moe>"]
edition = "2018"

[dependencies]
serenity = "0.8.7"
lazy_static = "1.4.0"
regex = { version = "1.5.6", default_features = false, features = ["std", "unicode"] }
